### ISSUE TITLE
خطا تبدیل میلادی به شمسی

### ISSUE THREAD

**Issue by ali-joghataei** [razeghi71/JalaliCalendar#1]
تاریخ 20-01-2017
رو یه بررسی کنید درست به تاریخ شمسی تبدیل نمیشه
تبدیلش میکنه به  30-10-1395
که باید بشه 01-11-1395

**Comment by razeghi71** [comment]
<div dir="rtl">
سلام @ali-joghataei
</div>

<div dir="rtl">
خیلی ممنون از گزارش خطاتون.
</div>

<div dir="rtl">
آیا در تبدیل به این نکته دقت کردین که ماه‌های کلاس GregorianCalendar جاوا از صفر شروع می‌شوند؟ (ماه ژانویه ماه صفرم است)
یعنی برای تبدیل این تاریخی که شما گفتین باید 
20-0-2017
به کلاس GregorianCalendar داده بشه.
</div>

**Comment by ali-joghataei** [comment]
بله دوست عزیز کد من به این شکل هست
JalaliCalendar jalaliDate = new JalaliCalendar(new GregorianCalendar(2017, 0, 20));

**Comment by razeghi71** [comment]
<div>
بله حق با شماست. انشالله طی دو سه روز آینده این مشکل رو رفع میکنم.
</div>
