### ISSUE TITLE
Wrong calcualtion from gregorian calendar

### ISSUE THREAD

**Issue by javaherisaber** [razeghi71/JalaliCalendar#4]
Hi
this library isn't working correctly
consider gregorian calendar of this date = 2019-6-29
we expect JalaliCalendar to return 1398/04/08
but actually returns 1398/05/07

**Comment by razeghi71** [comment]
Dear Mahdi, 
Thank you for your bug report,
I will work on it this weekend.

**Comment by TariRahil** [comment]
Hi
example 1:
current date : gregorian = 2020-10-05 and jalali = 1399-07-14 but jalaliCalenda return 1399-07-15 that is wrong
example 2:
current date : gregorian = 2020-09-30 and jalali = 1399-07-09 and jalaliCalenda return 1399-07-09 that is OK

**Comment by razeghi71** [comment]
@javaherisaber @TariRahil are you sure you're using the right 0 based Gregorian Calendar? if yes can you please paste here the snippet you're using?

**Comment by mohammedhossyn** [comment]
Hello dear Razeghi,
thanks for the project.
They are right my friend, actually that returns a month after current month.
Let's take a look:
![Screenshot (83)](https://github.com/razeghi71/JalaliCalendar/assets/110063355/5114d1e7-5fab-4f0e-b76a-3de534118f2e)

**Comment by mohammedhossyn** [comment]
Hello dear Razeghi,
thanks for sharing project.
Actually they are right my friend, that returns a month after current month,
G date: 2023-12-22 ---- P date: 1402-11-02

**Comment by razeghi71** [comment]
do you take into account that:

```
First of all I should note that java gregorian calenders month is 0 base
```

**Comment by razeghi71** [comment]
closing the issue as there is no response
