### ISSUE TITLE
1 day less

### ISSUE THREAD

**Issue by mackwu828** [razeghi71/JalaliCalendar#6]
current: 2020-4-26
convert to jalali : 1399-02-06 wrong!
correct : 1399-02-07

**Comment by peymanabbasi** [comment]
2021-4-25
1400-03-04 wrong

**Comment by micky396** [comment]
Hello 
Hope you are doing good 
I am getting one issue 1 day less can you please help me on this? as my project is dependent on this converter

**Comment by DJDrama** [comment]
No good
Wrong

**Comment by razeghi71** [comment]
@mackwu828 @peymanabbasi @DJDrama  are you sure you're using the right 0 based Gregorian Calendar? if yes can you please paste here the snippet you're using?

**Comment by razeghi71** [comment]
I'm closing this thread as I tested the above.
