### ISSUE TITLE
پیشنهاد توسعه

### ISSUE THREAD

**Issue by mehrdadashtari** [razeghi71/JalaliCalendar#7]
<div dir="rtl" lang="fa">سلام پیشنهادی دارم برای افزودن قابلیت نمایش رویداد به برنامه ای که توسعه دادید

الان که همه ی سیستم ها به اینترنت متصل هستند پیشنهاد میکنم ارتباط با ای پی آي های تقویم رو هم در این سورس خوب پیاده سازی کنید
خودم از این سرویس زیاد استفاده میکنم </div>
<a href="https://apieco.ir/api/farsicalendar">وب سرویس تقویم فارسی</a>

<div dir="rtl" lang="fa">اطلاعات خوبی ارائه میده مثل وقایع و مناسبت های هر روز و دریافت رویداد در حالت شمسی و قمری و میلادی</div>

**Comment by razeghi71** [comment]
هدف از توسعه‌ی این کتابخانه این بوده که من نتونستم یه کتابخانه پیدا کنم که خیلی ساده فقط کار تبدیل تاریخ رو انجام بده و بتونم ازش در پروژه‌هام استفاده کنم. برای همین اضافه کردن فیچرهای جدید خیلی جزو برنامه نیست. 


ولی استقبال میکنم اگر این مخزن ریپو رو فورک کنید و چیزایی که گفتید رو بهش اضافه کنید.
