### ISSUE TITLE
Wrong leap year detection

### ISSUE THREAD

**Issue by MikkiMouse** [razeghi71/JalaliCalendar#8]
Hi, 1404 year is leap year in Jalali calendar, but library does not define it that way.

`JalaliCalendar(1404, 1, 1).isLeap return false but it's not true`

Any date in 1404 year is being converted to the Gregorian calendar incorrectly.

Example:

```
JalaliCalendar(1404, 1, 1).toGregorian() == 21.03.2025 - incorrect
1.1.1404 in Jalali it is 20.03.2025 in Gregorian
```

It would be cool if this bug is being fixed. Thanks

**Comment by razeghi71** [comment]
Hi @MikkiMouse,

1404 is not a leap year, and the converted date is correct:

![Screenshot 2024-05-03 at 12 36 31](https://github.com/razeghi71/JalaliCalendar/assets/1843462/bb2a6f28-620a-43cf-bf06-481167334fbe)
